# v2rayNG optimized release rules for AGP 9.2 / R8 full mode.
#
# R8 9.1+ already repackages app classes by default. Keep this explicit so the intended
# hardening remains obvious even if build-tool defaults change later.
-repackageclasses
-allowaccessmodification

# Preserve only runtime metadata that reflection/serialization genuinely needs.
-keepattributes Signature,RuntimeVisibleAnnotations,RuntimeVisibleParameterAnnotations,AnnotationDefault,InnerClasses,EnclosingMethod

# Persisted DTO/MMKV/Gson payloads must keep field names for update compatibility, while their
# class names may still be renamed/repackaged and their bytecode may still be optimized.
-keep,allowoptimization,allowobfuscation,allowrepackage class com.v2ray.ang.dto.**
-keepclassmembers class com.v2ray.ang.dto.** {
    <fields>;
}

# Persisted enum constant names are part of saved configuration data. Keep those field names but
# still allow the enum classes themselves to be obfuscated/repackaged/optimized.
-keep,allowoptimization,allowobfuscation,allowrepackage enum com.v2ray.ang.enums.**
-keepclassmembers enum com.v2ray.ang.enums.** {
    <fields>;
}

# R8 full-mode Gson generic-signature handling. Gson 2.13 also ships consumer rules, but keeping
# these explicit protects anonymous TypeToken usages in this app across dependency changes.
-keep,allowobfuscation,allowshrinking,allowoptimization,allowrepackage class com.google.gson.reflect.TypeToken { *; }
-keep,allowobfuscation,allowshrinking,allowoptimization,allowrepackage class * extends com.google.gson.reflect.TypeToken

# WorkManager persists worker class names in its database. Preserve names/constructors so an app
# update cannot strand already-enqueued work, while allowing normal bytecode optimization.
-keepnames class * extends androidx.work.ListenableWorker
-keepclassmembers class * extends androidx.work.ListenableWorker {
    public <init>(android.content.Context, androidx.work.WorkerParameters);
}

# AndroidLibXrayLite is generated by gomobile and invokes Java callbacks from native code using
# exact class/method descriptors. This is the critical exception learned from the previous R8
# crash: do not rename, shrink, or repackage these bindings/callback implementations.
-keep class go.** { *; }
-keep class libv2ray.** { *; }
-keep class * implements libv2ray.CoreCallbackHandler { *; }
-keep class * implements libv2ray.ProcessFinder { *; }

# hev-socks5-tunnel JNI bridge must retain its Java/native descriptor.
-keep class com.v2ray.ang.service.TProxyService { *; }

# Preserve names/descriptors for any additional JNI entry points without broadly keeping unrelated
# app code. includedescriptorclasses protects parameter/return classes referenced by native calls.
-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

# Parcelable creators are discovered by the Android framework.
-keepclassmembers class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
